config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    respond_to do |format|
      format.html do
        flash[:warning] = "Template missing"
        redirect_to root_path
      end
      format.js { render template: 'users/modal.js.erb' }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
      format.html do
        flash[:warning] = "Template missing"
        redirect_to root_path
      end
      format.js { render template: 'users/modal.js.erb' }
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      flash[:success] = "User updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:first_name,:last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootstrapModal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.submit %>
<% end %> 

app/views/users/_modal.html.erb
<div class="modal fade" id="form_modal" role="modal">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <!-- <h4 class="modal-title">Modal Header</h4> -->
        <h4 class="modal-title text-center"><%= action_name.capitalize %> User</h4>
      </div>
      <div class="modal-body">
        <%= render 'users/form' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.js.erb
$("#myModal").html("<%= j render "modal"%>");
$('#form_modal').modal('show');

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to "#{user.full_name}", user %>
    </li>
  <% end %>

</ul>

<%= link_to "New User", new_user_path, remote: true, class: "btn btn-primary" %>
<div id="myModal"></div>

app/views/users/modal.js.erb
$("#myModal").html("<%= j render "modal"%>");
$('#form_modal').modal('show');

app/views/users/show.html.erb
<h1><%= @user.id %></h1>
<p><%= @user.first_name %></p>
<p><%= @user.last_name %></p>

<%= link_to "Edit", edit_user_path(@user), remote: true, class: "btn btn-info" %>
<%= link_to "HOME", root_path, class: "btn btn-danger" %>
<div id="myModal"></div>